config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :downloads

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/download.rb
# == Schema Information
#
# Table name: downloads
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  filepath   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Download < ActiveRecord::Base
  attr_accessible :filepath, :name

  validates :name, presence: true
  validates :filepath, presence: true
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @downloads = Download.all
  end

  def show
    @download = Download.find(params[:id])
    send_file "public/downloads/#{@download.filepath}"
  end

  def new
    @download = Download.new
  end

  def create
    @download = Download.new(params[:download])
    if @download.save
      flash[:success] = "Download item created."
      redirect_to downloads_path
    else
      render 'new'
    end
  end

  def edit
    @download = Download.find(params[:id])
  end

  def update
    @download = Download.find(params[:id])
    if @download.update_attributes(params[:download])
      flash[:success] = "Download updated"
      redirect_to downloads_path
    else
      render 'edit'
    end
  end

  def destroy
    Download.find(params[:id]).destroy
    flash[:success] = "Download destroyed."
    redirect_to downloads_path
  end

  private
    def admin_user
      redirect_to(signin_path) unless signed_in? && current_user.admin?
    end

end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/_download.html.erb
<li>
  <%= download.name %>
  | <%= link_to "download", download %>
  <% if current_user && current_user.admin? %>
    | <%= link_to "edit", edit_download_path(download) %>
    | <%= link_to "delete", download, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/downloads/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :filepath %>
<%= f.text_field :filepath %>

app/views/downloads/edit.html.erb
<% provide(:title, "Edit download") %>
<h1>Update download</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@download) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/downloads/index.html.erb
<% provide(:title, 'All downloads') %>
<h1>All downloads</h1>

<ul class="downloads">
  <%= render @downloads %>
</ul>
<%= link_to "New download", new_download_path if signed_in? && current_user.admin? %>

app/views/downloads/new.html.erb
<% provide(:title, 'New download') %>
<h1>New download</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@download) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create download", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>